SELECT
    *,
    {{ upuma('STATEFIP', 'PUMA')}} AS UPUMA,
    {{ eeo_tab_code('OCC')}} AS EEO_TAB_CODE,
    {{ degfieldr('DEGFIELDD')}} AS DEGFIELDR,
    {{ ager('AGE')}} AS AGER,
    {{ disability('VETDISAB', 'DIFFREM', 'DIFFPHYS', 'DIFFMOB', 'DIFFCARE', 'DIFFSENS', 'DIFFEYE', 'DIFFHEAR')}} AS DISABILITY,
    {{ educr('EDUCD')}} AS EDUCR,
    {{ hispanr('HISPAND')}} AS HISPANR,
    {{ racer('RACED')}} As RACER,
    {{ minoritystatr('RACED', 'HISPAND')}} AS MINORITYSTATR,
    {{ sexr('SEX')}} AS SEXR,
    {{ vetstatr('VETSTAT')}} AS VETSTATR,
    {{ fsregions('STATEFIP', 'UPUMA')}} AS FSREGIONS,
    {{ researchstation('STATEFIP')}} AS RESEARCHSTATION,
    {{ perwt_sum('UPUMA')}} AS perwt_sum_upuma,
    {{ perwt_sum('FSREGIONS')}} AS perwt_sum_fsregion,
    {{ perwt_sum('RESEARCHSTATION')}} AS perwt_sum_researchstation,
    {{ perwt_sum_per_degree('UPUMA')}} AS perwt_sum_per_degree_upuma,
    {{ perwt_sum_per_degree('FSREGIONS')}} AS perwt_sum_per_degree_fsregion,
    {{ perwt_sum_per_degree('RESEARCHSTATION')}} AS perwt_sum_per_degree_researchstation,
    {{ avg_age('UPUMA') }} AS avg_age_upuma,
    {{ avg_age('FSREGIONS') }} AS avg_age_fsregion,
    {{ avg_age('RESEARCHSTATION') }} AS avg_age_researchstation,
    {{ median_salary('UPUMA')}} AS median_salary_upuma,
    {{ median_salary('FSREGIONS')}} AS median_salary_fsregion,
    {{ median_salary('RESEARCHSTATION')}} AS median_salary_researchstation
FROM {{ ref('workingpop') }}