SELECT
    PERWT,
    PUMA,
    OCC,
    DEGFIELDD,
    AGE,
    VETDISAB,
	DIFFREM,
	DIFFPHYS,
	DIFFMOB,
	DIFFCARE,
	DIFFSENS,
	DIFFEYE,
	DIFFHEAR,
    EDUCD,
    HISPAND,
    RACED,
    SEX,
    VETSTAT,
    STATEFIP,
	INCWAGE,
    {{ upuma('STATEFIP', 'PUMA') }} AS UPUMA,
    {{ perwt_err('UPUMA')}} AS PERWT_ERR_UPUMA,
    {{ eeo_tab_code('OCC') }} AS EEO_TAB_CODE,
    {{ degfieldr('DEGFIELDD') }} AS DEGFIELDR,
    {{ ager('AGE') }} AS AGER,
    {{ disability('VETDISAB', 'DIFFREM', 'DIFFPHYS', 'DIFFMOB', 'DIFFCARE', 'DIFFSENS', 'DIFFEYE', 'DIFFHEAR') }} AS DISABILITY,
    {{ educr('EDUCD') }} AS EDUCR,
    {{ hispanr('HISPAND') }} AS HISPANR,
    {{ racer('RACED') }} AS RACER,
    {{ minoritystatr('RACED', 'HISPAND') }} AS MINORITYSTATR,
    {{ sexr('SEX') }} AS SEXR,
    {{ vetstatr('VETSTAT') }} AS VETSTATR,
    {{ fsregions('STATEFIP', 'UPUMA') }} AS FSREGIONS,
    {{ researchstation('STATEFIP') }} AS RESEARCHSTATION,
    {{ perwt_sum('UPUMA') }} AS perwt_sum_upuma,
    {{ perwt_sum('FSREGIONS') }} AS perwt_sum_fsregion,
    {{ perwt_sum('RESEARCHSTATION') }} AS perwt_sum_researchstation,
    {{ pct_demo('SEXR', "Male", 'UPUMA')}} AS pct_male_upuma,
    {{ pct_demo('SEXR', "Female", 'UPUMA')}} AS pct_female_upuma,
    {{ pct_demo('DISABILITY', "Disability", 'UPUMA')}} As pct_disabled_upuma,
    {{ pct_demo('DISABILITY', "No Disability", 'UPUMA')}} As pct_notdisabled_upuma,
    {{ pct_demo('VETSTATR', "Veteran", 'UPUMA')}} As pct_veteran_upuma,
    {{ pct_demo('VETSTATR', "Not a Veteran", 'UPUMA')}} As pct_nonveteran_upuma,
    {{ pct_demo('MINORITYSTATR', "Minority", 'UPUMA')}} As pct_minority_upuma,
    {{ pct_demo('MINORITYSTATR', "Non-Minority", 'UPUMA')}} As pct_nonminority_upuma,
    {{ perwt_sum_per_degree('UPUMA') }} AS perwt_sum_per_degree_upuma,
    {{ perwt_sum_per_degree('FSREGIONS') }} AS perwt_sum_per_degree_fsregion,
    {{ perwt_sum_per_degree('RESEARCHSTATION') }} AS perwt_sum_per_degree_researchstation,
    {{ avg_age('UPUMA') }} AS avg_age_upuma,
    {{ avg_age('FSREGIONS') }} AS avg_age_fsregion,
    {{ avg_age('RESEARCHSTATION') }} AS avg_age_researchstation
FROM {{ ref('workingpop') }}
